# Generated by Django 5.1.5 on 2025-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_videolog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolog",
            name="id",
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
