# Generated by Django 5.1.5 on 2025-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_videolog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
