# Generated by Django 5.1.5 on 2025-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_videolog_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="method",
            field=models.CharField(
                choices=[("youtube", "YOUTUBE"), ("invidious", "INVIDIOUS")],
                default="youtube",
                max_length=20,
            ),
        ),
    ]
