# Generated by Django 5.1.5 on 2025-03-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_video_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyWordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="videolog",
            name="keyword",
        ),
    ]
