# Generated by Django 5.1.5 on 2025-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_videolog_keyword"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="thumbnail_default",
            new_name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="video",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_high",
        ),
        migrations.RemoveField(
            model_name="video",
            name="thumbnail_medium",
        ),
        migrations.RemoveField(
            model_name="video",
            name="view_count",
        ),
    ]
