# Generated by Django 5.1.5 on 2025-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_rename_thumbnail_default_video_thumbnail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="id",
            new_name="video_id",
        ),
    ]
