# Generated by Django 5.1.5 on 2025-03-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_rename_id_video_video_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="video",
            name="videos_vide_channel_918466_idx",
        ),
        migrations.RemoveField(
            model_name="video",
            name="channel_id",
        ),
    ]
